version: '3.5'
services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - innersource

  migrate:
    image: migrate/migrate
    volumes:
    - ./repository/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure
    networks:
      - innersource

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links: 
      - db
      - migrate
    depends_on:
      - db
      - migrate
    environment:
      host: db
      port: 5432
      sslmode: disable
      server_port: 8080
    env_file:
      - .env
    restart: always
    networks:
      - innersource

networks:
  innersource:
      name: innersource