version: '3.5'
services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      - .env
    logging:
      driver: none
    ports:
      - "5000:5000"
    links:
      - "db:pgsql-server"

  migrate:
    image: migrate/migrate
    volumes:
    - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure

  api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    env_file:
      - .env
    links:
      - db
      - migrate
    depends_on:
      - db
      - migrate
    environment:
      host: db
      port: 5432
      sslmode: disable
      SERVER_PORT: ${SERVER_PORT}
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
